### PR TITLE
Make label specifications consistent.

### PR DESCRIPTION
**Pull request by bgrant0607**
and hopefully test CLA

### CODE REVIEW

**Comment by caniszczyk** [comment]
@bgrant0607 can you sign the CLA here? https://identity.linuxfoundation.org/projects/cncf

**Comment by bgrant0607** [comment]
There's no labeling, but we could extend our bot to do that.

**Comment by bgrant0607** [comment]
@caniszczyk I've sent in the Google CLA. What's the next step?

**Comment by caniszczyk** [comment]
@bgrant0607 you have to go here now that we received your corporate CLA:
https://identity.linuxfoundation.org/node/285/employee-signup

I would login via GitHub (assuming your google.com email address is the primary one)

**Comment by bgrant0607** [comment]
@caniszczyk Ok, that was easy. I signed in and got:

```
Welcome! You have been automatically assigned membership in Google and are authorized to contribute code to this project.
```

How do we make the cla check happen again?

**Comment by caniszczyk** [comment]
@bgrant0607 reach out to LF IT, it should happen almost instantaneously, looks like it works now

compared to googlebot, there's a few things I see missing:
- highlighting PRs with a "cla:no" or "cla:yes" tag depending on status
- a friendly PR message on how to sign the eCLA instead of relying on finding the "Details" hyperlink that comes back from the commit status

Anything else on your mind in terms of the experience? I want to make sure you're happy with it before we roll it out in k8s land.

**Comment by bgrant0607** [comment]
@caniszczyk We can extend our bot to manage labels and post notification messages to PRs, if you can provide the text to post.

One thing that has been useful for us for debugging CLA issues, especially for corporate CLAs, is access to the CLA database. Is there a means of manual lookup and override?

Also, is the mechanism capable of checking PRs with commits from multiple authors? If so, is any additional signup from those authors required?

**Comment by emsearcy** [comment]
Right now the CLA check happens every N minutes on a scheduled poll; we need to extend it to receive webhooks so it can happen instantly.  Adding a comment on the PR as well as pushing status API will be trivial.

Yes, our tool has a UI.  Organizations that have signed corporate CLAs can have organization managers who can view and manage their authorized employees and signed CLAs.  (If an organization signed the CCLA via the self-service interface, the person doing that is set up as the initial manager for that organization automatically.)  It's our first pass at the UI so it's not going to win any awards but the functionality is there.

Yes, PRs with multiple authors are individually checked.  In fact the person making the PR is irrelevant; it's only commit authors that are checked.

**Comment by dankohn** [comment]
Eric, it is an extremely high priority for CNCF to iterate the CLAbot to use
webhooks instead of polling and fully utilize the status API. We'd also like the
CLAbot to be a Github repo so that CNCF developers can make improvements to the
UI via pull request (with you remaining as committer, of course). Do you or
someone on your team have the time to focus on this next week? If not, would it
make sense for us to bring in a contractor to help?

On Fri, Jul 29, 2016 12:14 PM, Eric Searcy notifications@github.com wrote:
Right now the CLA check happens every N minutes on a scheduled poll; we need to
extend it to receive webhooks so it can happen instantly. Adding a comment on
the PR as well as pushing status API will be trivial.

Yes, our tool has a UI. Organizations that have signed corporate CLAs can have
organization managers who can view and manage their authorized employees and
signed CLAs. (If an organization signed the CCLA via the self-service interface,
the person doing that is set up as the initial manager for that organization
automatically.) It's our first pass at the UI so it's not going to win any
awards but the functionality is there.

Yes, PRs with multiple authors are individually checked. In fact the person
making the PR is irrelevant; it's only commit authors that are checked.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub , or mute the thread .

-- Dan Kohn <mailto: dan@linuxfoundation.org > Executive Director, Cloud Native Computing Foundation < https://cncf.io/ >
tel:+1-415-233-1000

**Comment by foxish** [comment]
@emsearcy Have there been any updates on this? We would like to start by switching to the CNCF bot on a single kubernetes repository, as a test. Would you be able to outline how we can get either the polling version, or the one using webhooks (if that effort is complete) up on a repository?

**Comment by dankohn** [comment]
@caniszczyk Could you please:
1. Create a new repo where we can discuss the status of the CLAbot, make feature requests, etc., even if the underlying code is not open source yet, because it is still too closely tied to the LF infrastructure.
2. Provide updates in an issue there on the current status.
3. Do a weekly update in that repo, after consulting with @emsearcy? This is one of the highest priority projects in CNCF and should not be hiding on this PR (though I'm fine to use the repo as a test bed, if it's helpful.) I'm happy to do a call instead/as well if that helps move things forward.

Cc @monadic

**Comment by caniszczyk** [comment]
@dankohn we'll track it here: https://github.com/cncf/foundation/issues/1

**Comment by dankohn** [comment]
Closing this PR as it is now tracked in https://github.com/cncf/foundation/issues/1

**Pull request closed without merging**
